Repository escape-link/escapelink-fe, pull requests merged in 2023-10, with the labels that each got.

#21 Add cypress testing
  cypress.config.js
  cypress/e2e/landing_page_spec.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
Labels: enhancement, Front End

#22 Create main.yml
  .github/workflows/main.yml
Labels: enhancement, Front End

#27 Feat/api calls
  src/App.js
  src/apiCalls.js
  src/components/Story/Story.js
Labels: enhancement, Front End

#29 Feat/chat
  package-lock.json
  package.json
  src/App.js
  src/apiCalls.js
  src/components/Chat/Chat.css
  src/components/Chat/Chat.js
Labels: enhancement, Front End

#30 Add PuzzleFour Component
  src/components/PuzzleFour/PuzzleFour.css
  src/components/PuzzleFour/PuzzleFour.js
  src/components/PuzzleOne/PuzzleOne.css
  src/components/PuzzleOne/PuzzleOne.js
  src/components/Room/Room.js
Labels: enhancement, Front End

#32 Add PuzzleFive component
  src/components/PuzzleFive/PuzzleFive.css
  src/components/PuzzleFive/PuzzleFive.js
  src/components/Room/Room.js
Labels: enhancement, Front End

#34 Feat/dark mode feature
  src/components/PuzzleFour/PuzzleFour.js
  src/components/Room/Room.css
  src/components/Room/Room.js
Labels: enhancement, Front End

#35 Feat/puzzle logic
  src/components/PuzzleOne/PuzzleOne.js
  src/components/PuzzleTwo/PuzzleTwo.js
  src/components/Room/Room.js
Labels: enhancement, Front End

#36 Feat/additional game logic
  src/PuzzleThree/PuzzleThree.css
  src/PuzzleThree/PuzzleThree.js
  src/components/PuzzleFive/PuzzleFive.js
  src/components/PuzzleFour/PuzzleFour.js
  src/components/PuzzleOne/PuzzleOne.css
  src/components/PuzzleOne/PuzzleOne.js
  src/components/PuzzleTwo/PuzzleTwo.js
  src/components/Room/Room.css
  src/components/Room/Room.js
Labels: enhancement, Front End

#39 Feat/disable buttons
  src/PuzzleThree/PuzzleThree.js
  src/components/PuzzleFive/PuzzleFive.js
  src/components/PuzzleFour/PuzzleFour.js
  src/components/PuzzleOne/PuzzleOne.js
  src/components/PuzzleTwo/PuzzleTwo.js
  src/components/Room/Room.css
  src/components/Room/Room.js
Labels: enhancement, Front End

#46 Feat/timer header
  public/EscapeLinkLogo.png
  src/App.js
  src/components/LandingPage/LandingPage.css
  src/components/RoomHeader/RoomHeader.css
  src/components/RoomHeader/RoomHeader.js
  src/components/RoomOne/RoomOne.js
Labels: enhancement, Front End

#42 docs: Add unfinished readme
  README.md
  public/escapelinklogo.png
Labels: enhancement, Front End

#50 Fix/conflicting components
  public/escapelinklogo.png
  src/App.js
  src/assets/EscapeLinkLogo.png
  src/components/Chat/Chat.js
  src/components/ChatWindow/ChatWindow.css
  src/components/ChatWindow/ChatWindow.js
  src/components/Context/WebSocketContext.js
  src/components/LandingPage/LandingPage.js
  src/components/Room/Room.css
  src/components/Room/Room.js
  src/components/RoomOne/RoomOne.js
  src/components/Story/Story.js
Labels: Front End

#52 Feat/error handling
  src/App.js
  src/components/ErrorHandling/ErrorHandling.css
  src/components/ErrorHandling/ErrorHandling.js
  src/components/LandingPage/LandingPage.js
  src/components/Story/Story.js
Labels: Front End

#54 Feat/websocket connection
  src/components/LandingPage/LandingPage.js
  src/components/PuzzleFive/PuzzleFive.js
  src/components/PuzzleFour/PuzzleFour.js
  src/components/PuzzleOne/PuzzleOne.js
  src/components/PuzzleThree/PuzzleThree.css
  src/components/PuzzleThree/PuzzleThree.js
  src/components/PuzzleTwo/PuzzleTwo.js
  src/components/RoomOne/RoomOne.js
  src/components/Story/Story.js
Labels: bug, Front End

#55 Feat/styling
  src/components/Chat/Chat.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/LandingPage/LandingPage.css
  src/components/LandingPage/LandingPage.js
  src/components/RoomOne/RoomOne.js
  src/components/Story/Story.css
  src/components/Story/Story.js
  src/components/VictoryPage/VictoryPage.css
  src/components/VictoryPage/VictoryPage.js
Labels: Front End

#57 Feat/cypress
  cypress/e2e/escape_room_spec.cy.js
  cypress/e2e/landing_page_spec.cy.js
  cypress/e2e/story_page_spec.cy.js
  package-lock.json
  package.json
  src/components/RoomHeader/RoomHeader.js
  src/components/RoomOne/RoomOne.css
  src/components/RoomOne/RoomOne.js
  src/components/Story/Story.css
  src/components/Story/Story.js
Labels: Front End

#60 Feat/error
  cypress/e2e/escape_room_spec.cy.js
  cypress/e2e/landing_page_spec.cy.js
  cypress/e2e/story_page_spec.cy.js
  src/App.js
  src/apiCalls.js
  src/components/Chat/Chat.js
  src/components/Cipher/Cipher.js
  src/components/Context/WebSocketContext.js
  src/components/ErrorHandling/ErrorHandling.css
  src/components/Header/Header.js
  src/components/LandingPage/LandingPage.js
  src/components/PuzzleOne/PuzzleOne.js
  src/components/RoomHeader/RoomHeader.css
  src/components/RoomHeader/RoomHeader.js
  src/components/RoomOne/RoomOne.css
  src/components/RoomOne/RoomOne.js
  src/components/Story/Story.js
  src/components/VictoryPage/VictoryPage.css
  src/components/VictoryPage/VictoryPage.js
Labels: Front End

#62 Pass tests
  src/apiCalls.js
  src/components/RoomOne/RoomOne.js
Labels: Front End

#63 Feature/production
  cypress/e2e/story_page_spec.cy.js
  src/apiCalls.js
  src/components/RoomOne/RoomOne.js
Labels: Front End
